### PR TITLE
Fixed the wrong path in Makefile.

### PR DESCRIPTION
**Pull request by shahzadlone**
Fixes the "make run-client issue".

### CODE REVIEW

**Comment by Mogball** [comment]
@shahzadlone does this need to be merged?

**Comment by shahzadlone** [comment]
Yes

**Comment by Mogball** [comment]
@dhillondeep who's responsible for reviewing this stuff

**Comment by dhillondeep** [comment]
I am working on this. So I will do that

**Comment by dhillondeep** [comment]
Won't merge

**Pull request closed without merging**
