### PR TITLE
Rough "Test Like" Implementation Done

### PR DESCRIPTION
**Pull request by shahzadlone**
Finished using wbinary and wjson to manipulate the packet according to our communication goal.
1) takes a packet and converts to binary bytes.
2) sends that binary packet to a server.
3) the server reads the packet.
4) if that packet is of type binary message then proceeds.
5) that packet is convert from binary to a packet struct.
6) that packet then is converted to JSON.

TODO: For now i left a dummy packet in the global, that i am using to test. We should have proper unit test for this and move that global testing packet after we figure out how we plan to use this.

### CODE REVIEW

**Comment by shahzadlone** [comment]
@dhillondeep

**Comment by dhillondeep** [comment]
I will test this soon and then I will merge this PR. Looks pretty good for now

**Comment by Mogball** [comment]
@shahzadlone Can you squash your commits?
Maybe like 3 or less

**Comment by Mogball** [comment]
oh I didn't realise we were squashing and merging on this repo (though we should) given that the commit history is still like using regular merge, in that case there was no point in having him squash the commits @dhillondeep

**Comment by dhillondeep** [comment]
History was kind of all over the place so I fixed and renamed some commits. Then just squashed the whole thing

**Comment by Mogball** [comment]
if you were gonna squash everything anyway why'd you rename the commits lol

**Comment by dhillondeep** [comment]
lol idk had some time so I did it

**Comment by Mogball** [comment]
you're crazy

**Comment by shahzadlone** [comment]
I wish github had a button like bitbucket that gives there merger an option to squash all commits to one when they merge a pull request.

**Comment by dhillondeep** [comment]
It does and that is what I did

**Comment by Mogball** [comment]
It's the standard merge option that should be used for all repos

**Pull request merged**
